name: Deploy Website CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          # Menghapus karakter whitespace/spasi yang tidak terlihat di awal/akhir
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//' > ~/.ssh/tes_server_polindra
          
          # Memastikan ada satu baris kosong di akhir file (SSH sering rewel soal ini)
          echo "" >> ~/.ssh/tes_server_polindra
          
          chmod 600 ~/.ssh/tes_server_polindra
          
          # Debug: cek apakah file kunci terbuat dengan benar (tidak akan membocorkan isi kunci di log)
          ls -l ~/.ssh/tes_server_polindra
          
          # Scan host
          ssh-keyscan -p 8022 -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          # Sinkronisasi file menggunakan rsync
          # -a: archive mode, -v: verbose, -z: compress, --delete: hapus file di server jika di repo sudah tidak ada
          rsync -avz --delete \
          -e "ssh -p 8022 -i ~/.ssh/tes_server_polindra -o StrictHostKeyChecking=no" \
          ./ \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.DEPLOY_PATH }}